'use client';

import { useState } from 'react';
import { ChevronDown } from 'lucide-react';
import { ResumeInsight } from '@/lib/types';
import { Button } from '@/components/ui/button';

export function AnalysisPanel({ insight }: { insight: ResumeInsight }) {
  const [open, setOpen] = useState(false);

  return (
    <div className="rounded-3xl border border-border bg-surface-elevated p-5">
      <div className="flex items-center justify-between gap-3">
        <div>
          <p className="text-xs uppercase tracking-[0.22em] text-text-tertiary">Expandable AI panel</p>
          <h3 className="mt-2 font-display text-2xl tracking-[-0.03em] text-text-primary">Improvement actions</h3>
        </div>
        <Button variant="secondary" size="sm" onClick={() => setOpen((prev) => !prev)}>
          {open ? 'Collapse' : 'Expand'} <ChevronDown size={15} className={open ? 'rotate-180 transition-transform' : 'transition-transform'} />
        </Button>
      </div>

      {open ? (
        <div className="mt-5 grid gap-3">
          {insight.suggestions.map((suggestion) => (
            <div key={suggestion} className="rounded-2xl border border-border bg-surface-muted px-4 py-3 text-sm text-text-secondary">
              {suggestion}
            </div>
          ))}
        </div>
      ) : (
        <p className="mt-4 text-sm text-text-secondary">Open this panel to view specific, high-impact edits generated by the AI engine.</p>
      )}
    </div>
  );
}
